export const articles = [
  {
    slug: "scaling-llms-enterprise",
    title: "Scaling LLMs for Enterprise Software Architecture",
    category: "AI & Machine Learning",
    readTime: "12 min read",
    date: "October 24, 2024",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1200",
    description: "How we integrate large language models into enterprise systems while maintaining performance and compliance.",
    intro: "As digital systems grow more complex, integrating AI into enterprise workflows requires architectural precision and reliability.",
    section1: { title: "The Decomposition Paradox", content: "Breaking systems into microservices introduces flexibility but also complexity. The challenge is balancing modularity with performance." },
    section2: { title: "Infrastructure as Code: The Blueprint", content: "Using IaC tools like Terraform and Kubernetes enables consistent deployments and scalable infrastructure patterns." },
    quote: "The premium feel of an architecture comes from the space between the elements—the APIs and the network.",
    points: [
      { title: "Event-Driven Orchestration", desc: "Reduce latency using async pipelines instead of synchronous calls." },
      { title: "Observability Layers", desc: "Monitor system health with real-time telemetry." },
      { title: "Edge Computation", desc: "Move processing closer to users for better performance." },
    ],
    author: { name: "Marcus Chen", role: "Lead Engineer", avatar: "https://i.pravatar.cc/100?img=3", bio: "Marcus is a senior engineer specializing in distributed systems and AI infrastructure." },
    featured: true,
  },
  {
    slug: "micro-interactions-psychology",
    title: "The Psychology of Micro-interactions",
    category: "UI/UX",
    readTime: "6 min read",
    date: "October 12, 2024",
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=1200",
    description: "How subtle animations improve user engagement and perception.",
    intro: "Micro-interactions create emotional feedback loops that enhance usability.",
    section1: { title: "Why Micro-interactions Matter", content: "They provide instant feedback and guide users through interactions." },
    section2: { title: "Designing Delight", content: "Small animations can significantly impact user satisfaction." },
    quote: "Users don't notice good UX — but they feel it.",
    points: [
      { title: "Feedback", desc: "Immediate visual response improves usability." },
      { title: "Clarity", desc: "Helps users understand system behavior." },
    ],
    author: { name: "Dina Hartono", role: "Product Designer", avatar: "https://i.pravatar.cc/100?img=5", bio: "Dina focuses on crafting human-centered digital experiences." },
    featured: false,
  },
  {
    slug: "data-as-product",
    title: "Beyond the Dashboard: Data as Product",
    category: "Business",
    readTime: "8 min read",
    date: "October 08, 2024",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200",
    description: "Turning analytics into monetizable products for B2B enterprises.",
    intro: "Data is no longer just reporting — it's a product.",
    section1: { title: "From Insight to Product", content: "Companies are monetizing data through APIs and analytics platforms." },
    section2: { title: "Scalability", content: "Data pipelines must be reliable and scalable to support growth." },
    quote: "Data becomes valuable when it drives decisions.",
    points: [
      { title: "Monetization", desc: "Turn insights into revenue streams." },
      { title: "Automation", desc: "Reduce manual reporting processes." },
    ],
    author: { name: "Rizky Pratama", role: "Data Architect", avatar: "https://i.pravatar.cc/100?img=8", bio: "Rizky builds scalable data platforms for enterprises." },
    featured: false,
  },
  {
    slug: "server-side-components",
    title: "Server-Side Components vs. Client Hydration",
    category: "Web Dev",
    readTime: "7 min read",
    date: "October 03, 2024",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200",
    description: "A performance comparison of the latest rendering techniques in the React ecosystem.",
    intro: "RSC changes how we think about React performance.",
    section1: { title: "The Hydration Problem", content: "Hydrating large component trees on the client is expensive. Server components solve this." },
    section2: { title: "When to Use Each", content: "The key is knowing which components need interactivity and which don't." },
    quote: "The fastest code is code that doesn't run on the client.",
    points: [
      { title: "Zero JS Bundle", desc: "Server components ship no JavaScript to the browser." },
      { title: "Streaming", desc: "Progressively render UI as data becomes available." },
    ],
    author: { name: "Kevin Liu", role: "Senior Frontend Engineer", avatar: "https://i.pravatar.cc/100?img=12", bio: "Kevin specializes in React performance and modern web architecture." },
    featured: false,
  },
  {
    slug: "future-of-scalable-microservices",
    title: "The Future of Scalable Microservices",
    category: "Web Dev",
    readTime: "10 min read",
    date: "October 24, 2024",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200",
    description: "How microservices architecture is evolving for high-scale distributed systems.",
    intro: "Microservices are fundamental—but scaling them introduces new challenges.",
    section1: { title: "Service Decomposition", content: "Finding the right service boundaries is more art than science." },
    section2: { title: "Service Mesh", content: "Tools like Istio handle cross-cutting concerns at the infrastructure level." },
    quote: "Good architecture is about making the important decisions first.",
    points: [
      { title: "Service Mesh", desc: "Handle observability and security at the infrastructure layer." },
      { title: "Event Sourcing", desc: "Maintain system state with an immutable event log." },
    ],
    author: { name: "Alex Sadino", role: "CTO & Founder", avatar: "https://i.pravatar.cc/100?img=15", bio: "Alex is a software architect with 15+ years building high-scale distributed systems." },
    featured: false,
  },
  {
    slug: "clean-code-principles",
    title: "Clean Code Principles Every Dev Should Know",
    category: "Business",
    readTime: "5 min read",
    date: "September 28, 2024",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200",
    description: "The timeless principles that separate good code from great code.",
    intro: "Writing code that others can read is a professional skill.",
    section1: { title: "Naming Matters", content: "Descriptive variable names eliminate the need for comments in most cases." },
    section2: { title: "Single Responsibility", content: "Each function should do one thing and do it well." },
    quote: "Any fool can write code that a computer understands. Good programmers write code humans understand.",
    points: [
      { title: "DRY", desc: "Don't repeat yourself — abstract common patterns." },
      { title: "SOLID", desc: "Five principles for maintainable object-oriented design." },
    ],
    author: { name: "Sarah Kim", role: "Engineering Lead", avatar: "https://i.pravatar.cc/100?img=20", bio: "Sarah coaches engineering teams on software craftsmanship." },
    featured: false,
  },
];
